#shampoo
nome: "Care Blonde Savior Shampoo 300ml"
preço: 299
descrição: O Blonde Savior Shampoo foi desenvolvido para cabelos danificados e descoloridos.
 Shampoo sem sulfato, com Ácido Glicólico e Creatina. Recupera e fortalece os fios ao mesmo 
 tempo em que hidrata instantaneamente, dando ao cabelo uma aparência incrível e saudável instantaneamente.
<strong>Adequado para:</strong> Cabelos danificados e descoloridos.

#condicionador
nome: Care Color Brillianz Conditioner 250ml
preço: 199
descrição: Condicionador de tratamento para cabelos com coloração que estabiliza a cor, 
fixando o pigmento no interior dos fios.
<strong>Adequado para:</strong> Cabelos coloridos.

#mascara
nome: Care Blonde Savior Mask 200ml
preço: 99
descrição: Care Blonde Savior Mask 200ml
Máscara de tratamento intensivo para cabelos danificados e descoloridos. 
Recupera e hidrata os fios. Reduz os danos causados pela descoloração e melhora 
a qualidade do fio ao longo do tempo, além de fortalecer os fios e reduzir 
consideravelmente a quebra
<strong>Adequado para:</strong> Cabelos danificados e descoloridos
